authenticate_service_url: https://authenticate.pomerium.app

signing_key_file: '/pomerium/ec_private.pem'
autocert: true

jwt_claims_headers:
  X-Pomerium-Claim-Email: email
  X-Pomerium-Claim-User: user
  X-Pomerium-Claim-Name: name

routes:
  - from: https://verify.localhost.pomerium.io
    to: http://verify:8000
    policy:
      - allow:
          or:
            - email:
                is: angelosanag@protonmail.com
            - claim/Name: Anagnostopoulos Angelos
      - deny:
          and:
            - email:
                starts_with: admin

    pass_identity_headers: true

  - from: https://grafana.localhost.pomerium.io
    to: http://grafana:3000
    allow_any_authenticated_user: true
    pass_identity_headers: true
  
  - from: https://pythonserver.localhost.pomerium.io
    to: http://hello:8000
    policy:
      - allow:
          and:
            - domain:
                is: protonmail.com
