version: '3.8'

services:
  
  # client_computer:
  #   image: alpine:latest
  #   container_name: client
  #   networks:
  #     - test
  #   tty: true

  database:
    image: postgres
    container_name: test_database
    volumes:
      - /media/angelos/Medium_boi/docker_volumes:/var/lib/postgresql/data
      - ./databases/test:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=angelos
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=test_db
    ports:
      - 5432:5432
    networks:
      - test

  server:
    build:
      context: ./servers/test
    container_name: test_server
    ports:
      - 8080:8080
    networks:
      - test

networks:
  test: