version: '3.3'

services:
  
  # policy_enforcement_point:
  #   build: ./servers/pep
  #   container_name: pep
  #   networks:
  #     - test
  
  # authentication_server:
  #   build: ./servers/authentication
  #   container_name: authentication
  #   networks:
  #     - test
  
  # authorization_server:
  #   build: ./servers/authorization
  #   container_name: authorization
  #   networks:
  #     - test
  
  # certificate_authority:
  #   build: ./servers/certauth
  #   container_name: certauth
  #   networks:
  #     - test
  
  device_inventory:
    image: postgres
    container_name: device_db
    volumes:
      - ./databases/devices:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=angelos
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=device_db
    ports:
      - 54322:5432
    networks:
      - test

  users_inventory:
    image: postgres
    restart: always
    container_name: users_db
    volumes:
      - ./databases/users:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=angelos
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=users_db
    ports:
      - 54323:5433
    networks:
      - test

  # certificate_inventory:
  #   image: redis
  #   container_name: ca_db
  #   ports: 
  #     - 6379:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL    
  #   networks:
  #     - test

networks:
  test:
  # certificates:
  # policies:
  # resources: