version: '3.3'

services:
  
  # client_computer:
  #   image: alpine:latest
  #   container_name: client
  #   networks:
  #     - test
  #   tty: true

  test_database:
    image: postgres
    container_name: device_container
    volumes:
      - ./databases/test:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=angelos
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=ligma_db
    ports:
      - 5432:5432
    networks:
      - test

  test_server:
    build:
      context: ./servers/test
    container_name: server
    depends_on:
      - test_database
    ports:
      - 4444:4444
    networks:
      - test


networks:
  test: