version: '3.8'

services:
  
  # client_computer:
  #   image: alpine:latest
  #   container_name: client
  #   networks:
  #     - test
  #   tty: true

  database:
    image: postgres
    container_name: user_auth_db
    volumes:
      - postgredata:/var/lib/postgresql/data
      - ./databases/authentication:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=angelos
      - POSTGRES_PASSWORD=example
      # - POSTGRES_DB=auth_db
    ports:
      - 5432:5432
    networks:
      - authentication

  server:
    build:
      context: ./servers/authentication
    container_name: auth_server
    ports:
      - 8080:8080
    networks:
      - authentication

networks:
  authentication:

volumes:
  postgredata: {}